### PR TITLE
feature: added management command for simple use of create_public_tenant

### PR DESCRIPTION
**Pull request by jgentil**
# I'm helping!

## Checklist

- [X] I have double checked that there are no unrelated changes in this pull request (old patches, accidental config files, etc.)
- [X] I have created at least one test case for the changes I have made
- [X] I have updated the documentation for the changes I have made
- [X] I have added my changes to the `CHANGELOG.md`

## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## Related issue(s)

- Implements #564

### CODE REVIEW

**Comment by jgentil** [comment]
@Dresdn tagging you since I can't assign a reviewer.  We added this command locally to our project and I figured it would be a good contribution.

**Comment by Dresdn** [comment]
Thanks @jgentil! Appreciate the contribution.

**Comment by Dresdn** [comment]
@jgentil FYI that the tests are failing, but I did take this opportunity to update all dependencies to latest supported ones

**Comment by jgentil** [comment]
Ah I need to fix the f string to support Python 3.7.

**Comment by Dresdn** [comment]
I just cleaned up the dependencies of EOL versions, so 3.7 isn't an issue anymore.

**Comment by Dresdn** [comment]
Thanks! I'll do a release here, too, so we can get this and Django 5.0 support out the door.

**Pull request merged**
