### PR TITLE
BREAKING CHANGES::Now returning created tenant from provision_tenant utility function

### PR DESCRIPTION
**Pull request by Wizely99**
# I'm helping!

## Checklist

- [x] I have double checked that there are no unrelated changes in this pull request (old patches, accidental config files, etc.)
- [x] I have created at least one test case for the changes I have made
- [ ] I have updated the documentation for the changes I have made
- [ ] I have added my changes to the `CHANGELOG.md`

## Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

### CODE REVIEW

**Comment by Wizely99** [comment]
I am working on the docs but before I would like to get the feedback from you guys.
There was an issue about returning the tenant from the provision_tenant function but I think it was closed for some reason.
This PR  has addressed.I am eager to help more

**Comment by Dresdn** [comment]
This is great @Wizely99! I've had this as a todo for some time, so I appreciate the work put into it. I don't really have much feedback on it, but will merge in once the docs are done.

Thank you!

**Comment by Wizely99** [comment]
Hello @Dresdn .
I've updated the docs you check them out..

**Comment by Dresdn** [comment]
Hi @Wizely99. The docs look good, and good call on missing a RST formatter. Since you mentioned `rstfmt`, I added that to the `tool.poetry.group.test.dependencies` and then added a check to the test workflow.

Thank you for the contribution!

**Pull request merged**
