### PR TITLE
added support for multi-tenant types

### LINKED ISSUE #354: Support for multi type tenants
## Detailed Description
 django-tenants supports multiple types of tenants as described here: https://django-tenants.readthedocs.io/en/latest/use.html#multi-types-tenants. It does not appear this is compatible with django-tenant-users out of the box since the provision_tenant function is used to wrap the creation of tenants and there is no way to pass extra fields to the tenant when it is created, you need to be able to pass the tenant type to the constructor otherwise it can't run the migrations as it doesn't know what apps are installed for that tenant type.

## Possible Implementation
 Modify the provision_tenant function to allow passing extra fields to the users tenant type constructor

### PR DESCRIPTION
**Pull request by Wizely99**
## Pull Request type

**Feature**

## Description

This pull request adds three new features to the `create_public_tenant` function:

* Checks if the password is provided and skips `set_unusable_password` if it is.
* Adds the `tenant_extra_data` argument for the `type` field.
* Allows passing of extra tenant info.

Also it adds the following features to the `provision_tenant` function:

* The ability to pass a schema name.
* The ability to pass additional tenant data.
* The ability to check if the tenant type is valid if multi-tenant is enabled.

## Related issues

* Closes #354
* Refs #354

* Please let me know if there is anything I can do.

### CODE REVIEW

**Comment by Dresdn** [comment]
@Wizely99 - thanks for the submission!

Couple things:

1. Could you add some tests for the additions?
2. The current tests fail due to changes in the `provision_tenant()` params. We shouldn't break backward compatibility.

I'm all for updating things like `provision_tenant()` and `create_user()`, so if we should take a first step at breaking those things for a 2.x release, I'd be on board.

**Comment by Dresdn** [comment]
That's a good call out, and I went ahead and removed the pytest coverage requirement to let Codecov handle the coverage level changes.

Take a look at the coverage and let me know if you're able to write some tests to bring this up a bit, especially with a new feature like this.

**Comment by Wizely99** [comment]
@Dresdn - Hello, thank you for your response. I've been able to write tests for tenant types. You can now rerun the workflow.I hope it now works like charm..!

**Comment by Dresdn** [comment]
@Wizely99 - looks really good overall! I went a little nuts though as I was cleaning some things up.

Since `create_public_tenant()` now has a return value, I'm wondering if we go ahead and change how `tasks.provision_tenant()` returns too, since things like #44 exist.

We can then just bump the major version with breaking changes.

**Comment by Wizely99** [comment]
@Dresdn  Yeah, sure. I thought of that myself, but I didn't want to break compatibility. I'll take that into account and make changes to the docs too.

**Pull request merged**
